<?php

return array (
  'name' => 'LGK',
  'beian' => '',
  'cdnurl' => '',
  'version' => '1.2.7',
  'timezone' => 'Asia/Shanghai',
  'forbiddenip' => '',
  'languages' => 
  array (
    'backend' => 'zh-cn',
    'frontend' => 'zh-cn',
  ),
  'fixedpage' => 'dashboard',
  'categorytype' => 
  array (
    'default' => 'Default',
    'page' => 'Page',
    'article' => 'Article',
    'test' => 'Test',
  ),
  'configgroup' => 
  array (
    'basic' => 'Basic',
    'email' => 'Email',
    'dictionary' => 'Dictionary',
    'user' => 'User',
    'example' => 'Example',
  ),
  'mail_type' => '1',
  'mail_smtp_host' => 'smtpdm-ap-southeast-1.aliyun.com',
  'mail_smtp_port' => '465',
  'mail_smtp_user' => 'support@lgker.ltd',
  'mail_smtp_pass' => 'fhiJyneif55kRX6o',
  'mail_verify_type' => '2',
  'mail_from' => 'support@lgker.ltd',
  'withdraw_handling_fee' => '0.3',
  'withdraw_handling_fee_lowest' => '100',
  'transfer' => '1',
  'transfer_mining_handling_fee' => '0',
  'base_price' => '1.585',
  'publish_stock' => '0',
  'publish_base' => '300000',
  'stock_need_origin' => '85',
  'buy_min_stock' => '10',
  'buy_max_stock' => '5000000',
  'produce_profit' => '1',
  'deal_handling_fee' => '5',
  'deal_bonus_fee' => '3',
  'static_shop_profit' => '5',
  'dynamic_shop_profit' => '5',
  'publish_trade_time_begin' => '10:00:00',
  'publish_trade_time_end' => '23:00:00',
  'pay_order_time' => '10800',
  'release_order_time' => '86400',
  'publish_origin_rate' => '0',
  'publish_lowest_price' => '1.585',
  'publish_highest_price' => '1.585',
  'bank_name' => '王苗苗',
  'bank' => '中国银行',
  'sub_bank' => '安阳永明路支行',
  'bank_card' => '6217 8580 0011 3511 510',
  'android_version' => '1.3.1',
  'single_buy_max_base' => '50000',
  'buy_deal_handing_fee' => '10',
  'publish_lowest_number' => '500',
  'publish_highest_number' => '3000',
  'lowest_take_num' => '100',
  'highest_take_num' => '200',
  'coin_take_times' => '4',
  'car_arrive_time' => '120',
  'coin2_price' => '0.791232',
);